### ISSUE TITLE
How to define functions

### ISSUE THREAD

**Issue by jakecraige** [losingkeys/4clojure.el#7]
I can't figure out how I'm supposed to define functions that will be checked properly. 

Example:

``` clojure
;; 4Clojure Question 46
;;
;; Write a higher-order function which flips the order of the arguments of an input function.
;;
;; Use M-x 4clojure-check-answers when you're done!

(defn __ [f]
  (fn [& args]
    (apply f (reverse args))))

(= 3 ((__ nth) 2 [1 2 3 4 5]))

(= true ((__ >) 7 8))

(= 4 ((__ quot) 2 8))

(= [1 2 3] ((__ take) [1 2 3 4 5] 3))
```

When I run `4clojure-check-answers` I get

```
Test 0 failed.
java.lang.RuntimeException: Unable to resolve symbol: __ in this context, compiling:(NO_SOURCE_PATH:0)
```

Is it possible to define a function that works? Rather than inlining it on each line?

**Comment by losingkeys** [comment]
Unfortunately not at the moment. This plugin Just grabs the first expression that used to be a blank.

**Comment by koolkt** [comment]
If anyone is interested there is this solution http://endlessparentheses.com/be-a-4clojure-hero-with-emacs.html
